main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls'), name='portfolio'),
    path('aniwatch/', include('aniwatch.urls'), name='aniwatch'),
]

portfolio/urls.py
from django.urls import include, path
from . import views

app_name = 'portfolio'
urlpatterns = [
    path('', views.index, name='index'),
    path('form', views.form, name='form'),
]

portfolio/models.py
from django.db import models
from django.core.files.storage import FileSystemStorage
import uuid, os


# Create your models here.
class Me(models.Model):
    def get_available_name(self, name, max_length=None):
        name = 'staticfiles/portfolio/assets/music/'
        try:
            music_file = None
            for i in os.listdir(name):
                if len(i) > 5:
                    music_file = i
                os.remove(name+i)
            return name+i
        except:
            return name+"music.none"

    name=models.CharField(max_length=100, default='Anish Chapagai')

    # This image link will contain 3 image links seperated by commas
    # Can't make it list here because default python list type is not supported
    # So will make list in views by splitting
    image_link = models.TextField(default="")
    music = models.FileField(upload_to=get_available_name, default="")

    def __str__(self):
        return self.name

class Projects(models.Model):
    name = models.CharField(max_length=300, unique=True, default=uuid.uuid1)
    priority = models.IntegerField(default=uuid.uuid1)
    tools = models.CharField(max_length=300, default="")
    description = models.TextField(default="")
    image = models.CharField(max_length=200, default="")
    link = models.CharField(max_length=200, default="")
    def __str__(self):
        return self.name

class Events(models.Model):
    name = models.CharField(max_length=300, unique=True, default=uuid.uuid1)
    description = models.TextField(default="")
    image_link = models.CharField(max_length=300, default="")
    def __str__(self):
        return self.name

class Contacts(models.Model):
    name = models.CharField(max_length=100)
    url = models.CharField(max_length=300)

    def __str__(self):
        return self.name

portfolio/views.py
from django.http import JsonResponse
from django.shortcuts import render
from django.core.mail import send_mail
from django.conf import settings
import json
import logging
from . import models

logging.basicConfig(filename='contact_debug.log', encoding='utf-8', level=logging.DEBUG)

# Create your views here.
def index(request):
    Me = models.Me.objects.all()[0]
    context = {
        'Me':{
            'Name':Me.name,
            'Image':Me.image_link.split(','),
            },
        'Projects':[{
            'Name':i.name,
            'Tools':i.tools.split(','),
            'Description':i.description,
            'Image':i.image,
            'ProjectLink':i.link
            }for i in models.Projects.objects.all()],
        'Event':[{
            'Name':i.name,
            'Description':i.description,
            'Image':i.image_link
            } for i in models.Events.objects.all()],
        'Contact':[{'IconSocial':i.name,
                    'LinkSocial':i.url} for i in models.Contacts.objects.all()],
        'iconGithub':'https://github.com/fluidicon.png',   
    }
    return render(request, 'portfolio/index.html', context)

def form(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        try:
            # Send mail
            send_mail(
                'Portfolio Message',
                f'Name: {str(data["name"])}\n\
                Email: {str(data["email"])}\n\
                Phone: {str(data["phone"])}\n\
                Message: {str(data["message"])}\n\
                UserAgent: {str(request.headers["User-Agent"])}',
                settings.EMAIL_HOST_USER,
                [settings.EMAIL_DEST_USER],
                fail_silently=False)
            return JsonResponse({'Status':'Success'})
        except Exception as e:
            logging.debug("SMTP send_mail"+str(e))
            return JsonResponse({'Status':'Failed'})
    return JsonResponse({'Status':'You nauty nauty ;)'})

portfolio/templates/portfolio/index.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{{ Me.Name }} | Portfolio</title>

	<link rel="stylesheet" type="text/css" href="{% static 'portfolio/css/index.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'portfolio/css/projects.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'portfolio/css/participations.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'portfolio/css/contact.css' %}">
</head>
<body>
	<nav>
		<ul>
			<li class="intro selected"><a href="#intro">Introduction</a></li>
			<li class="academics"><a href="#academics">Academics</a></li>
			<li class="projects"><a href="#projects">Projects</a></li>
			<li class="participations"><a href="#participations">Participations</a></li>
			<li class="arts"><a href="#sketches">Cheap Sketches</a></li>
			<li class="contact"><a href="#contact">Contact</a></li>
		</ul>
	</nav>
	<div class="view_container" >
		<div class="bg_image visible" id="intro">
			<img class="image1" src="{{ Me.Image.0 }}">
			<img class="image2" src="{{ Me.Image.1 }}">
			<img class="image3" src="{{ Me.Image.2 }}">
			<div class="gradient_container"></div>
			<div class="bg_text">
				<ul>
				</ul>
			</div>
		</div>
		<div id="academics" class="">
			
		</div>
		<div id="projects" class="hidden">
			<div class='projects_container'>
				<ul>
					{% for i in Projects %}
						<li class='project'>
							<div class="title_bar">
								<div class='title'>{{ i.Name }}</div>
								<ul class='tools_container'>
									{% for t in i.Tools %}	
										<li class='tools'>
											<img src="{% static 'portfolio/assets/icons/' %}{{ t }}.svg">
										</li>
									{% endfor %}
								</ul>
								<span></span>
							</div>
							<div class='description'>
								<div class='text'>
									{{ i.Description }}
								</div>
								<div class='photo'>
									<a href="{{ i.ProjectLink }}">
										<img src="{{ i.Image }}">
										<div class='github_popup'>
											<span>
												<img src="{{ iconGithub }}">
											</span>
										</div>
									</a>
								</div>
							</div>
						</li>
					{% endfor %}	
				</ul>
			</div>
		</div>
		<div id="participations" class="hidden">
			<div class='par_container'>
				<ul class='par_ul'>
					{% for event in Event %}
						<li class='par_li'>
							<h3>{{ event.Name }}</h3>
							<div class='par_positioning_container'>
								<p>
									{{ event.Description }}
								</p>
								<a href="{{ event.Image }}" target='_blank'>
									<div class='par_image'>
										<div class='par_image_filter'></div>
										<img src="{{ event.Image }}">
									</div>
								</a>
							</div>
						</li>
					{% endfor %}
				</ul>
			</div>
		</div>
		<div id="arts" class="hidden"></div>
		<div id="contact" class="hidden">
			<div class="cont_container">
				<h1>I'd love to hear from you</h1>
				<div class="cont_description_container">
					<div class="cont_art">
						<div class="cont_head"></div>
						<div class="cont_body_container">
							<div class="cont_body"></div>
							<div class="cont_left_hand"></div>
							<div class="cont_right_hand"></div>
						</div>
						<div class="cont_plat_container">
							<div class="cont_platform"></div>
							<div class="cont_thigh1"></div>
							<div class="cont_thigh2"></div>
						</div>
						<div class=cont_foot_container>
							<div class="cont_foot1"></div>
							<div class="cont_foot2"></div>
						</div>
					</div>
					<div class="cont_separator"></div>
					<div class="cont_description">
						<p>
							Got a project you'd like me to work on?<br>
							Or how about a friendly chat?<br>
							Or maybe let's go cycling together.<br>
						</p>
					</div>
				</div>
				<div class="cont_links">
					<ul>
						{% for i in Contact %}
							<li>
								<a href="{{ i.LinkSocial }}">
									<img src="{% static 'portfolio/assets/icons/' %}{{ i.IconSocial }}.svg">
								</a>
							</li>
						{% endfor %}
							<li id="cont_anon_message">
								<a href="#">
									<img src="{% static 'portfolio/assets/icons/anonymous.svg' %}">
								</a>								
							</li>
					</ul>
				</div>
				<div class="cont_anonymous">
					<div class='cont_anon_exit'>
						<div class="cont_anon_exit_left"></div>
						<div class="cont_anon_exit_right"></div>
					</div>
					<h1>Write to me here anonymously</h1>
					<form method="post" id="form" onsubmit="return false">
						{% csrf_token %}
						<div class="cont_anon_left">
							<input type="text" name="name" placeholder="Nickname*" required>
							<input type="text" name="email" placeholder="Email">
							<input type="text" name="phone" placeholder="Phone Number">
						</div>
						<textarea maxlength="1000" name="message" placeholder="Message*" required></textarea>
					</form>
					<button data-value="{% url 'portfolio:form' %}" form="form">Glide it away</button>
				</div>
			</div>
		</div>
		<button class="move_down" class="hidden">↓</button>
	</div>
	<div class="music paused">
		<audio loop>
			<source src="{% static 'portfolio/assets/music/music' %}">
		</audio>
	</div>
</body>
<script type="text/javascript" src="{% static 'portfolio/js/index.js' %}"></script>
</html>