aniwatch/urls.py
from django.urls import include, path
from . import views

app_name = 'aniwatch'
urlpatterns = [
    path('', views.index, name='index'),
    path('anime/<str:anime_url>/', views.anime, name='anime'),
    path('anime/<str:anime_url>/<int:episode>', views.anime, name='anime_play'),
    path('query', views.query, name='query'),
    path('upload/', views.MovieUpload.as_view(), name='upload'),

    # Navbar calls
    path('ongoing/', views.ongoing, name='ongoing'),
    path('recently-popular/', views.popular, name='recently-popular'),
    path('hot/', views.hot, name='hot'),
    path('genres/', views.genres, name='genres'),

]

main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls'), name='portfolio'),
    path('aniwatch/', include('aniwatch.urls'), name='aniwatch'),
]

aniwatch/models.py
from django.db import models
import uuid

class Video(models.Model):
    name = models.CharField(max_length=200, unique=True, default=uuid.uuid1)
    image_link = models.CharField(max_length=200, default="#")
    url = models.CharField(max_length=200, default="#")
    summary = models.TextField(default="")
    genre = models.CharField(max_length=200, default="")
    status = models.CharField(max_length=100, default="")
    episodes = models.IntegerField(default=1)
    released = models.IntegerField(default=1)
    anime_type = models.CharField(max_length=100, default="")
    def __str__(self):
        return self.name

class Recents(models.Model):
    name = models.CharField(max_length=300, unique=True, default=uuid.uuid1)
    def __str__(self):
        return self.name

class NewReleases(models.Model):
    name = models.CharField(max_length=300, unique=True, default=uuid.uuid1)
    last_ep = models.IntegerField(default=0)
    def __str__(self):
        return self.name

class Recommended(models.Model):
    name = models.CharField(max_length=300, unique=True, default=uuid.uuid1)
    def __str__(self):
        return self.name
class Hot(models.Model):
    name = models.CharField(max_length=300, unique=True, default=uuid.uuid1)
    def __str__(self):
        return self.name
class Popular(models.Model):
    name = models.CharField(max_length=300, unique=True, default=uuid.uuid1)
    def __str__(self):
        return self.name

aniwatch/views.py
from django.views.decorators.clickjacking import xframe_options_exempt
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render
from django.views import View
from bs4 import BeautifulSoup

import io, csv, json, requests, os
from . import models
from .templatetags import scraper

def index(request):
    # Store dict containing trending and recommended
    if request.method == 'POST':
        return render(request, 'aniwatch/error.html', {'method':'Please don\'t POST'})
    context = {
        'Recents':[{'Title':i.name,
                    'Url':models.Video.objects.get(name=i.name).url,
                    'Image':models.Video.objects.get(name=i.name).image_link
                    } for i in models.Recents.objects.all()[:10]],
        'New':[{'Title':i.name,
                        'Url':models.Video.objects.get(name=i.name).url,
                        'Image':models.Video.objects.get(name=i.name).image_link
                        } for i in models.NewReleases.objects.all()[:10]],
        'Recommended':[{'Title':i.name,
                        'Url':models.Video.objects.get(name=i.name).url,
                        'Image':models.Video.objects.get(name=i.name).image_link
                        } for i in models.Recommended.objects.all()[:10]],
        }
    return render(request, 'aniwatch/index.html', context)

def query(request):
    if request.method == 'GET':
        return render(request, 'aniwatch/error.html', {'method':"You cant just Get, ploxx"})
    
    # pull video information from Video model
    anime = {'Query':str(request.POST['anime_name']),
            'Anime':[{'Title':i.name,
                        'Url':i.url,
                        'Image':i.image_link
                        }for i in models.Video.objects.filter(name__startswith=str(request.POST['anime_name']))[:20]
                    ]
            }
    return render(request, 'aniwatch/query.html', anime)


@xframe_options_exempt
def anime(request, anime_url, episode=False):
    # Return a page with video

    obj = models.Video.objects.get(url=anime_url)
    context = {'Anime':obj,
                # This conditional episode below will handle if the page is first clicked
                # or page with video has to be served
                'Servers': scraper.ScrapeAnime.getServers(obj.url, "1" if not episode else episode),
                'iframe':episode
    }
    return render(request, 'aniwatch/anime.html', context)

def queryEpisodesJson(request, anime_url, episode):
    # Fetch streaming url of that episode
    url = f"https://gogoanime.sk/{anime_url}-episode-{episode}"
    soup = BeautifulSoup(
            requests.get(url).text, 'html.parser')
    url = soup.find('div',class_="play-video").iframe.get("src")
    return JsonResponse(json.dumps({"Url":url}), safe=False);


class MovieUpload(View):
    def get(self, request):
        context = {
            'headings':['Name', 'Image', 'Summary', 'Genre', 'Episodes', 'Url', 'Type', 'Released']
        }
        return render(request, 'aniwatch/upload_csv.html', context)

    def post(self, request):
        if str(request.POST['key']) != os.environ['dj_key']:
            return render(request, 'aniwatch/error.html', {'method':'User not authorized to update database'})

        file = io.TextIOWrapper(request.FILES['data'].file)
        database = csv.DictReader(file)
        database = list(database)
        #'Name', 'Image', 'Summary', 'Genre', 'Type', 'Episodes', 'Status', 'Url']
        obj = [
            models.Video(
                name = row['Name'],
                image_link = row['Image'],
                summary = row['Summary'],
                genre = row['Genre'],
                status = row['Status'],
                episodes = row['Episodes'],
                url = row['Url'],
                anime_type = row['Type'],
                released = row['Released'],
                )
            for row in database
            ]
        try:
            bulk_obj = models.Video.objects.bulk_create(obj)
            return render(request, 'aniwatch/error.html', {'method':'Data Imported Successfully'})
        except Exception as e:
            return render(request, 'aniwatch/error.html', {'method':f'Failed to import Data:    {e}'})

def popular(request):
    # Filter dubbed anime
    filtered_ongoing_anime = list()
    for i in models.Popular.objects.all():
        if not 'dub' in i.name.lower():
            filtered_ongoing_anime.append(i)

    anime = {
        'Query':'Recently Popular',
        'Anime':[{'Title':i.name,
                'Url':models.Video.objects.get(name=i.name).url,
                'Image':models.Video.objects.get(name=i.name).image_link
                }for i in filtered_ongoing_anime[:20]
            ]
    }
    return render(request, 'aniwatch/query.html', anime)

def hot(request):

    # Filter dubbed anime
    filtered_ongoing_anime = list()
    for i in models.Hot.objects.all():
        if not 'dub' in i.name.lower():
            filtered_ongoing_anime.append(i)

    anime = {
        'Query':'Hot',
        'Anime':[{'Title':i.name,
                'Url':models.Video.objects.get(name=i.name).url,
                'Image':models.Video.objects.get(name=i.name).image_link
                }for i in filtered_ongoing_anime[:20]
            ]
    }
    return render(request, 'aniwatch/query.html', anime)

def genres(request):
    return render(request, 'aniwatch/error.html', {'method':'Need some time to implement this'})
def ongoing(request):

    # Filter dubbed anime
    filtered_ongoing_anime = list()
    for i in models.Video.objects.filter(status='Ongoing'):
        if not 'dub' in i.name.lower():
            filtered_ongoing_anime.append(i)

    anime = {'Query':'Genre: Ongoing',
            'Anime':[{'Title':i.name,
                        'Url':i.url,
                        'Image':i.image_link
                        } for i in filtered_ongoing_anime[:20]
                    ]
            }
    return render(request, 'aniwatch/query.html', anime)

class UpdateConsole(View):
    def get(self, request):
        context = dict()
        return render(request, 'aniwatch/updater_console.html', context)

    def post(self, request):
        return HttpResponse('hemlo')

aniwatch/templates/aniwatch/anime.html
{% extends 'aniwatch/base.html' %}
{% load template_filters %}

{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'aniwatch/css/anime.css' %}">
    <style>
        .main{
            background-image: url("{{ Anime.image_link }}");
        }
    </style>
{% endblock style %}
    <h1>{{ Anime.name }}</h1>
{% block body %}
    <div class='main'{% if iframe %} style="display:none" {% endif %}>
        <div class='details'>
            <ul>
                <li class='title'><i><span>Name:   </span></i>{{ Anime.name }}</li>
                <li class='genre'><i><span>Genre:   </span></i>{{ Anime.genre|joiner }}</li>
                <li class='status'><i><span>Status:   </span></i>{{ Anime.status }}</li>
                <li class='type'><i><span>Type:   </span></i> {{ Anime.type }}</li>
                <li class='description'><i><span>Description:   </span></i>{{ Anime.summary }}</li>
                <li style="display:none" class="associated_url" data-url="{{ Anime.url }}"></li>
            </ul>
        </div>
    </div>
    {% if iframe %}    
        <h2 style='text-align: center; letter-spacing: 3px;'>{{ Anime.name }} | Episode:{{ iframe }}</h2>
    {% endif %}
    <div class='player' {% if not iframe %} style="display:none" {% endif %}>
        <iframe src="{{ Servers.0.Url }}" allowfullscreen="true" frameborder="0" marginwidth="0" marginheight="0" scrolling="no"></iframe>
    </div>
    <div class='below'>
        <div class='servers' style="display: none;">
            <h3>Available Servers</h3>
            <ul>
                <!-- Place Server Lists here from javascript or prerendered --->
                {% for i in Servers %}
                    <li><a href="#" data-url='{{ i.Url }}'>{{ i.Name }}</a></li>
                {% endfor %}
            </ul>
        </div>
        <div class='episode_list'>
            <h2>Episodes</h2>
            <ul class='list'>
                {% for i in Anime.episodes|range_ %}
                <a href="{% url 'aniwatch:anime_play' Anime.url i %}" {% if i == iframe %}class='selected'{% endif %}>
                    <li class='ep_{{ i }}'> Ep: {{i}} </li>
                </a>
                {% endfor %}
            </ul>
        </div>
        <div class = 'comments_container'>
            <h2>Comments</h2>
            <h3>Not Implemented</h3>
        </div>
    </div>
{% endblock body %}
{% block scripts %}
    <script type="text/javascript" src="{% static 'aniwatch/js/anime.js' %}"></script>
{% endblock scripts %}

aniwatch/templates/aniwatch/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>
            AniWatch
        </title>
        <link rel="stylesheet" href="{% static 'aniwatch/css/base.css' %}">
        <script type="text/javascript" src="{% static 'aniwatch/js/base.js' %}"></script>
        {% block style %}
        {% endblock style %}
    </head>
    <nav>
        <h2>
            <a href="{% url 'aniwatch:index' %}">ANI<span>WATCH</span></a>
        </h2>
    
        <div class="flex-nav-middle">
            <a href="{% url 'aniwatch:hot' %}"><li class="hot"> Hot</li></a>
            <a href="{% url 'aniwatch:recently-popular' %}"><li class="recently-popular">Recently Popular</li></a>
            <a href="{% url 'aniwatch:genres' %}"><li class="genres">Genres</li></a>
            <a href="{% url 'aniwatch:ongoing' %}"><li class="ongoing">Ongoing</li></a>
        </div>
        <div class="flex-nav-right">
            <li class="inp" style="display: none">
                <form action="{% url 'aniwatch:query' %}" method="post">
                    {% csrf_token %}
                    <input type="text" name="anime_name" placeholder="Anime Name Here(Original)">
                </form>
            </li>
            <li class="search">
                <img src="{% static 'aniwatch/images/svgs/search.svg' %}" alt="search">
            </li>
            <li class="theme">
                <img src="{% static 'aniwatch/images/svgs/sun.svg' %}" alt="mode">
            </li>
            <li class="settings">
                <img src="{% static 'aniwatch/images/svgs/settings.svg' %}" alt="settings">
            </li>
        </div>
    </nav>
    <body>
        {% block body %}
            
        {% endblock body %}
    </body>
    <footer>Created with &hearts; by<a href="https://github.com/needl3">Needle</a></footer>
    {% block scripts %}
    {% endblock scripts %}
</html>

aniwatch/templates/aniwatch/error.html
{% extends 'aniwatch/base.html' %}
{% load static %}

{% block body%}
	<h2 style="text-align: center;font-size: 5em;margin-top: 1em;">Hi Cutiepie!</h2>
	<p style="text-align:center;font-size:3em;margin:1em;padding: 1em"><span style="color: aqua"> {{ method }}</span></p>
{% endblock body%}

aniwatch/templates/aniwatch/index.html
{% extends 'aniwatch/base.html' %}
{% load static %}

{% block style %}
        <link rel="stylesheet" href="{% static 'aniwatch/css/index.css' %}">
        <script type="text/javascript" src="{% static 'aniwatch/js/index.js' %}"></script>
{% endblock style %}

{% block body %}
    <div class="recent">
        <h2>Recents</h2>
        <ul class="recent-items">
            {% for i in Recents %}
                <li>
                    <a href="{% url 'aniwatch:anime' i.Url %}">
                        <img src="{ i.Image }" alt="{{i.Name}}-image">
                        <p>{{ i.Name }}</p>
                    </a>
                </li>
                {% endfor %}
        </ul>
    </div>
    <div class="trending">
        <h2>New Releases</h2>
        <ul class="trending-items">
            {% for i in New %}
                <li>
                    <a href="{% url 'aniwatch:anime' i.Url %}">
                        <img src="{{ i.Image }}" alt="{{i.Name}}-image">
                        <p>{{ i.Title }}</p>
                    </a>
                </li>
            {% endfor %}
        </ul>
        </div>
    </div>
    <div class="recommended">
        <h2>Recommended</h2>
        <ul class="recommended-items">
            {% for i in Recommended %}
                <li>
                    <a href="{% url 'aniwatch:anime' i.Url %}">
                        <img src="{{ i.Image }}" alt="{{i.Name}}-image">
                        <p>{{ i.Title }}</p>
                    </a>
                </li>
           {% endfor %} 
        </ul>
    </div>
{% endblock body %}

aniwatch/templates/aniwatch/query.html
{% extends 'aniwatch/base.html' %}

{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'aniwatch/css/query.css' %}">
{% endblock style %}

{% block body %}
	<div class='query_container'>
		<h2>Result for: <span>{{ Query }}</span></h2>
		<ul class='query_set'>
			{% for anime in Anime %}
				<li>
	                <a href="{% url 'aniwatch:anime' anime.Url %}">
	                    <img src="{{ anime.Image }}" alt="{{anime.Title}}">
	                    <p>{{ anime.Title }}</p>
	                </a>
				</li>
			{% endfor %}
		</ul>
	</div>
{% endblock body %}

aniwatch/templates/aniwatch/updater_console.html
{% extends 'aniwatch/base.html' %}

{% load static %}

{% block style %}
	<link rel="stylesheet" type="text/css" href="{% static 'aniwatch/css/console.css' %}">
{% endblock style %}

{% block body %}
	
{% endblock body %}

aniwatch/templates/aniwatch/upload_csv.html
{% extends 'aniwatch/base.html' %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'aniwatch/css/upload_csv.css' %}">
{% endblock style %}

{% block body %}
    <div class='form'>
        <h4>Import CSV</h4>
        <p>Make sure the csv contains headings as</p>
        <ul>
            {% for columns in headings %}
                <li>{{ columns }}</li>
            {% endfor %}
        </ul>
        <form method="post" enctype="multipart/form-data">
             {% csrf_token %}
            <input type="file" name="data"><br>
            <input type="password" name="key" placeholder="Secret Key Here">
            <button type="submit">Upload</button>        
      </form>
    </div>
{% endblock%}